### ISSUE TITLE
Segmentation fault in spruce protein test in CI

### ISSUE THREAD

**Issue by ijpulidos** [choderalab/asapdiscovery#480] opened 2023-09-20 17:05 UTC
We have been consistently getting a segmentation fault for the CI tests. Namely the [`test_spruce_protein[mers]` test](https://github.com/choderalab/asapdiscovery/actions/runs/6242281217/job/16945951393#step:7:1028).

It is only happening on the Linux CI tests. I cannot reproduce this locally using my linux workstation, all tests are running fine there.

**Comment by JenkeScheen** [comment] 2023-09-25 16:43
perhaps this is a test we can skip? might not be needed to run this test on *all* targets we have. MERS can be problematic due to 1) large system size 2) 'raw' state of the crystal (i.e. the post-processing workflow has not been optimized in the same standard as Sars2 Mpro, diamond-side). @kaminow @apayne97 thoughts?

**Comment by hmacdope** [comment] 2023-10-02 21:14
@ijpulidos  @JenkeScheen  I couldn't reproduce this locally either, my best guess is that making the DUs is too memory hungry for the GHA runners, takes quite a while on my box. I will XFail them.

**Comment by ijpulidos** [comment] 2023-10-02 21:16
@hmacdope My guess is that we are hitting some kind of resource limit when running all tests in the same workflow, I'm testing separating the workflows in #493 to see if that helps fixing it.

**Comment by ijpulidos** [comment] 2023-10-02 21:16
also related to #265

**Comment by hmacdope** [comment] 2023-10-02 21:21
Okie dokie, good idea, lets see if splitting them up works, I will put up a draft for xfailing them as well and then we can just close it if splitting them works.

**Comment by ijpulidos** [comment] 2023-10-02 21:34
I think separating the tests is the way to go, since modeling tests that were failing in [our current CI](https://github.com/choderalab/asapdiscovery/actions/runs/6374310977/job/17298809066#step:7:1645) are now passing in #493 [here](https://github.com/choderalab/asapdiscovery/actions/runs/6385598878/job/17330665224?pr=493#step:7:173).

That said, there's a docking tests that is still failing, that one would probably need to be marked/xfailed or reviewed if we really need it.

**Comment by hmacdope** [comment] 2023-10-02 21:40
OK awesome, thats great we figured out a way to get it to work. Are you good to take charge of splitting up the tests @ijpulidos? Is the idea to have a seperate run for  each subpackage or just for some of the worst offenders. In the worst case it would be 7x subpackages x 2 python version x 2 os so 28 runs which seems a little excessive. Perhaps we could either do the worst offenders, IMHO `docking` and `modelling` as you did in #493 or find some other way to trim down from a full matrix.
 
The failure in docking is a legitimate one #496, I will sort that out.

**Comment by ijpulidos** [comment] 2023-10-02 21:44
@hmacdope I just updated the description on #493 with this information.

**Closed** 2023-10-02 22:52 UTC
Labels: testing
